import removeLatinChars from './latins';

const firstName = [
  "Adrián",
  "Agustín",
  "Alberto",
  "Alejandro",
  "Alex",
  "Alexander",
  "Alexis",
  "Alonso",
  "Andrés Felipe",
  "Ángel",
  "Anthony",
  "Antonio",
  "Bautista",
  "Benicio",
  "Benjamín",
  "Carlos",
  "Carlos Alberto",
  "Carlos Eduardo",
  "Carlos Roberto",
  "César",
  "Cristóbal",
  "Daniel",
  "Dariela",
  "David",
  "Diego",
  "Dylan",
  "Eduardo",
  "Emiliano",
  "Emmanuel",
  "Enmanuel",
  "Enrique",
  "Erik",
  "Ernesto",
  "Ethan",
  "Fabián",
  "Facundo",
  "Felipe",
  "Félix",
  "Félix María",
  "Fernando",
  "Francisco",
  "Francisco Javier",
  "Gabriel",
  "Gaspar",
  "Gustavo Adolfo",
  "Hugo",
  "Ian",
  "Iker",
  "Isaac",
  "Jacob",
  "Javier",
  "Jayden",
  "Jeremy",
  "Jerónimo",
  "Jesús",
  "Jesús Antonio",
  "Jesús Víctor",
  "Joaquín",
  "Johanna",
  "Jorge",
  "Jorge  Alberto",
  "Jorge Luis",
  "José",
  "José Antonio",
  "José Daniel",
  "José David",
  "José Francisco",
  "José Gregorio",
  "José Luis",
  "José Manuel",
  "José Pablo",
  "Josué",
  "Juan",
  "Juan Ángel",
  "Juan Carlos",
  "Juan David",
  "Juan Esteban",
  "Juan Ignacio",
  "Juan José",
  "Juan Manuel",
  "Juan Pablo",
  "Juan Sebastián",
  "Julio",
  "Julio Cesar",
  "Justin",
  "Kevin",
  "Lautaro",
  "Liam",
  "Lian",
  "Lorenzo",
  "Lucas",
  "Luis",
  "Luis Alberto",
  "Luis Eduardo",
  "Luis Emilio",
  "Luis Fernando",
  "Manuel",
  "Manuel Antonio",
  "Marco Antonio",
  "Mario",
  "Martín",
  "Mateo",
  "Matías",
  "Maximiliano",
  "Maykel",
  "Miguel",
  "Miguel Ángel",
  "Nelson",
  "Noah",
  "Oscar",
  "Pablo",
  "Pedro",
  "Rafael",
  "Ramón",
  "Raúl",
  "Ricardo",
  "Rigoberto",
  "Roberto",
  "Rolando",
  "Samuel",
  "Samuel David",
  "Santiago",
  "Santino",
  "Santos",
  "Sebastián",
  "Thiago",
  "Thiago Benjamín",
  "Tomás",
  "Valentino",
  "Vicente",
  "Víctor",
  "Victoria",
  "Víctor Hugo",
  "Víctor Manuel",
  "Víctor Sebastián",
  "Wesley",
  "Wilfredo",
  "Yago",
  "Yamil",
  "Yamir",
  "Yeray",
  "Yisus",
  "Yolanda",
  "Ysidro",
  "Ysidro Manuel",
  "Ysidro Sebastián",
  "Ysmael",
  "Yosayri",
  "Yoscar",
  "Yosmar",
];
const lastName = [
  "Garcia",
  "Gonzalez",
  "Rodriguez",
  "Fernandez",
  "Lopez",
  "Balcacer",
  "Martinez",
  "Sanchez",
  "Perez",
  "Gomez",
  "Martin",
  "Jimenez",
  "Rosario",
  "Ruiz",
  "Hernandez",
  "Diaz",
  "Moreno",
  "Alvarez",
  "Muñoz",
  "Romero",
  "Alonso",
  "Gutierrez",
  "Navarro",
  "Torres",
  "Dominguez",
  "Vazquez",
  "Ramos",
  "Gil",
  "Ramirez",
  "Serrano",
  "Blanco",
  "Suarez",
  "Suriel",
  "Molina",
  "Morales",
  "Ortega",
  "Delgado",
  "Castro",
  "Ortiz",
  "Rubio",
  "Marin",
  "Sanz",
  "Nuñez",
  "Iglesias",
  "Medina",
  "Garrido",
  "Santos",
  "Castillo",
  "Cortes",
  "Lozano",
  "Guerrero",
  "Cano",
  "Prieto",
  "Mendez",
  "Calvo",
  "Cruz",
  "Gallego",
  "Vidal",
  "Leon",
  "Herrera",
  "Marquez",
  "Peña",
  "Cabrera",
  "Flores",
  "Campos",
  "Vega",
  "Diez",
  "Fuentes",
  "Carrasco",
  "Caballero",
  "Nieto",
  "Reyes",
  "Aguilar",
  "Pascual",
  "Herrero",
  "Santana",
  "Lorenzo",
  "Hidalgo",
  "Montero",
  "Ibañez",
  "Gimenez",
  "Ferrer",
  "Duran",
  "Vicente",
  "Benitez",
  "Mora",
  "Santiago",
  "Arias",
  "Vargas",
  "Carmona",
  "Crespo",
  "Roman",
  "Pastor",
  "Soto",
  "Saez",
  "Velasco",
  "Soler",
  "Moya",
  "Esteban",
  "Parra",
  "Bravo",
  "Gallardo",
  "Rojas",
  "Pardo",
  "Merino",
  "Franco",
  "Espinosa",
  "Izquierdo",
  "Lara",
  "Rivas",
  "Silva",
  "Rivera",
  "Casado",
  "Arroyo",
  "Redondo",
  "Camacho",
  "Rey",
  "Vera",
  "Fajardo",
  "Otero",
  "Luque",
  "Galan",
  "Montes",
  "Rios",
  "Sierra",
  "Segura",
  "Carrillo",
  "Marcos",
  "Marti",
  "Soriano",
  "Mendoza",
];

export const generateRandomData = () => {
  const randFirstIndex = Math.floor(Math.random() * firstName.length);
  const randLastIndex = Math.floor(Math.random() * lastName.length);
  const firstNameValue = firstName[randFirstIndex];
  const lastNameValue = lastName[randLastIndex];
  const fullName = `${firstNameValue} ${lastNameValue}`;
  const email = `${removeLatinChars(fullName.replaceAll(" ", ".")).toLowerCase()}@gmail.com`;
  const phone = `+1(8${
    [0, 2, 4][Math.floor(Math.random() * [0, 2, 4].length)]
  }9)-${Math.floor(Math.random() * 9)}${Math.floor(
    Math.random() * 9
  )}${Math.floor(Math.random() * 9)}-${Math.floor(
    Math.random() * 9
  )}${Math.floor(Math.random() * 9)}${Math.floor(
    Math.random() * 9
  )}${Math.floor(Math.random() * 9)}`;

  return {
    fullName,
    email,
    phone,
  };
};
